sensitivity:
  # multiplier
  level: 1.0
  # whether to normalize
  normalize: true

audio:
  # something technical (leave alone)
  device: 7
  # ???
  channels: [1]
  # subsampling???
  downsample: 1
  # visible time slot
  window: 200
  # interval for refreshing plot (not needed)
  interval: 30
  # use pca in inference step
  bPCA: true
  # length of PCA update window
  pca_window: 2000
flask:
  # black padding as a proportion of screen size
  padding: 0.02
  # path of model folder to load
  path: ['fire', 'clouds_pca', 'cosmos_pca', 'abstract_pca', 'richter_pca', 'water', 'pollock', 'droplets', 'honeycomb']
